authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('adminapp.urls', namespace='superadmin')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('__debug__', include(debug_toolbar.urls)),
    path('', include('mainapp.urls')),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', null=True, blank=True)
    age = models.PositiveIntegerField(verbose_name='Age', null=True, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('superadmin:users_detail', args=[str(self.id)])

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    # def clean_age(self):
    #     data = self.cleaned_data['age']
    #     if data < 18:
    #         raise forms.ValidationError("Вы слишком молоды!")
    #
    #     return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    # def clean_age(self):
    #     data = self.cleaned_data['age']
    #     if data < 18:
    #         raise forms.ValidationError("Вы слишком молоды!")
    #
    #     return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'Log In'

    login_form = ShopUserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': next
    }

    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'User Registration'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'Edit User'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
    {% block title %}
    {% endblock title %}
    {% block css %}
<!--        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock css %}
</head>
<body>
	<div class="container">
        <div class="user_data">
            {% block content %}
            {% endblock content %}
        </div>
	</div>
    {% block js %}
    {% endblock js %}
</body>
</html>

templates/authapp/edit.html
{% extends 'authapp/base.html' %}

{% block title %}
    <title>Edit User</title>
{% endblock title %}

{% block content %}
    <h2>Edit User</h2>
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="Save">
        <button class="btn btn-round form-control last">
        <a href="{% url 'main' %}" class="cancel_button">Cancel</a>
    </button>
    </form>
    </br>

    <div class="user_avatar">
        <img src="/media/{{ user.avatar }}">
    </div>
{% endblock content %}

templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Log in</title>
{% endblock title %}

{% block content %}
    <h2>Log in</h2>
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Log in">
    </form>
{% endblock content %}

templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>User Registration</title>
{% endblock title %}

{% block content %}
    <h2>User Registration</h2>
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Sign Up">
    </form>
{% endblock %}