adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('forbidden/', adminapp.ForbiddenView.as_view(), name='forbidden'),

    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/', adminapp.UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/', adminapp.UsersDetailView.as_view(), name='users_detail'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/', adminapp.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', adminapp.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/', adminapp.ProductsCreateView.as_view(), name='product_create'),
    path('products/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products_list'),
    path('products/<int:pk>/', adminapp.ProductsDetailView.as_view(), name='product_detail'),
    path('products/update/<int:pk>/', adminapp.ProductsUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductsDeleteView.as_view(), name='product_delete'),

    path('', adminapp.AdminHomeView.as_view(), name='admin_home'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('adminapp.urls', namespace='superadmin')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('__debug__', include(debug_toolbar.urls)),
    path('', include('mainapp.urls')),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView,  DeleteView
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect


class AdminMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

    def get_test_func(self):
        return self.test_func

    def dispatch(self, request, *args, **kwargs):
        user_test_result = self.get_test_func()()
        if not user_test_result:
            return redirect('adminapp:forbidden')
        return super().dispatch(request, *args, **kwargs)


class ForbiddenView(TemplateView):
    template_name = 'adminapp/forbidden.html'


class AdminHomeView(LoginRequiredMixin, AdminMixin, TemplateView):
    template_name = 'adminapp/base.html'


# Users Views

class UsersListView(LoginRequiredMixin, AdminMixin, ListView):
    model = ShopUser
    context_object_name = 'users'
    template_name = 'adminapp/users/users_list.html'
    login_url = 'authapp:login'


class UsersDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = ShopUser
    context_object_name = 'user'
    template_name = 'adminapp/users/users_detail.html'
    login_url = 'authapp:login'


class UsersCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = ShopUser
    fields = '__all__'
    template_name = 'adminapp/users/users_create.html'
    login_url = 'authapp:login'


class UsersUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = ShopUser
    fields = '__all__'
    context_object_name = 'user'
    template_name = 'adminapp/users/users_edit.html'
    login_url = 'authapp:login'


class UsersDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = ShopUser
    context_object_name = 'user'
    template_name = 'adminapp/users/users_delete.html'
    success_url = reverse_lazy('superadmin:users_list')
    login_url = 'authapp:login'


# Categories Views

class CategoryListView(LoginRequiredMixin, AdminMixin, ListView):
    model = ProductCategory
    context_object_name = 'categories'
    template_name = 'adminapp/categories/category_list.html'
    login_url = 'authapp:login'


class CategoryDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = ProductCategory
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_detail.html'
    login_url = 'authapp:login'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        category_pk = self.kwargs.get('pk')
        context['products'] = Product.objects.filter(category=category_pk)
        return context


class CategoryCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = ProductCategory
    fields = '__all__'
    template_name = 'adminapp/categories/category_create.html'
    login_url = 'authapp:login'


class CategoryUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = ProductCategory
    fields = '__all__'
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_edit.html'
    login_url = 'authapp:login'


class CategoryDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = ProductCategory
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_delete.html'
    success_url = reverse_lazy('superadmin:category_list')
    login_url = 'authapp:login'


# Products Views

class ProductsListView(LoginRequiredMixin, AdminMixin, ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'adminapp/products/products_list.html'
    login_url = 'authapp:login'


class ProductsDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'adminapp/products/products_detail.html'
    login_url = 'authapp:login'


class ProductsCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = Product
    fields = '__all__'
    template_name = 'adminapp/products/products_create.html'
    login_url = 'authapp:login'


class ProductsUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = Product
    fields = '__all__'
    context_object_name = 'product'
    template_name = 'adminapp/products/products_edit.html'
    login_url = 'authapp:login'


class ProductsDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'adminapp/products/products_delete.html'
    login_url = 'authapp:login'

    def get_success_url(self):
        product = Product.objects.filter(id=self.kwargs['pk'])[0]
        category_pk = product.category.pk

        return reverse_lazy('superadmin:category_detail', kwargs={'pk': category_pk})

templates/adminapp/users/users_create.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Create User
{% endblock title %}

{% block content %}
    <h1>New User</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/adminapp/users/users_delete.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Delete {{ user }}
{% endblock title %}

{% block content %}
    <h1>Delete {{ user }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ user }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/adminapp/users/users_detail.html
{% extends 'adminapp/base.html' %}

{% block title %}
    {{ user }}
{% endblock title %}

{% block content %}
<div class="user-entry">
    <h2>{{ user }}</h2>
    <div
            class="user_record {% if not user.is_active %}not_active{% endif %}">
        <img
                src="/media/{{ user.avatar|default:'users_avatars/default.jpg' }}"
                alt="{{ user.username }}">
        <div class="user_role">
            {% if user.is_superuser %}
            Admin
            {% else %}
            User
            {% endif %}
            <button>
                <a href={% url 'superadmin:user_update' user.pk %}>
                Edit
                </a>
            </button>
            <button>
                <a href={% url 'superadmin:user_delete' user.pk %}>
                Delete
                </a>
            </button>
        </div>
        <div class="user_name">
            <p><strong>{{ user.username }}</strong></p>
            <p>
                {% if user.first_name %}
                <b>{{ user.first_name|title }}</b>
                {% if user.last_name %}
            <p>{{ user.last_name|title }}</p>
            {% endif %}
            {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ user.age }} years old
        </div>
        <div class="user_email">
            email:<br>
            {{ user.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ user.last_login }}
        </div>
    </div>
    <br>
    <a href="{% url 'adminapp:users_list' %}"
       class="btn btn-secondary btn-lg active btn-block"
       role="button" aria-pressed="true">Return
    </a>
    <br>
    <div/>
    {% endblock content %}

templates/adminapp/users/users_edit.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Edit {{ user }}
{% endblock title %}

{% block content %}
    <h1>Edit {{ user }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/adminapp/users/users_list.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Users
{% endblock title %}

{% block content %}
    <div class="users_list">
        <a href="{% url 'superadmin:user_create' %}"
           class="btn btn-primary btn-lg active"
           role="button" aria-pressed="true">Create New User
        </a><br><br>
        {% for user in users %}
            <div class="card">
                <div class="card-header">
                <span class="font-weight-bold">
                    <a href="{% url 'superadmin:users_detail' user.pk %}">{{ user }}</a>
                </span> &middot;
                    <span class="text-muted">
                    {% if user.is_superuser %}
                        Admin
                    {% else %}
                        User
                    {% endif %}
                </span>
                </div>
                <div class="card-body">
                    User Info Here
                </div>
                <div class="card-footer text-center text-muted">
                    <a href="{% url 'superadmin:user_update' user.pk %}">Edit</a> |
                    <a href="{% url 'superadmin:user_delete' user.pk %}">Delete</a>
                </div>
            </div>
            <br/>
        {% endfor %}
    </div>
{% endblock %}