adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('forbidden/', adminapp.ForbiddenView.as_view(), name='forbidden'),

    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/', adminapp.UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/', adminapp.UsersDetailView.as_view(), name='users_detail'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/', adminapp.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', adminapp.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/', adminapp.ProductsCreateView.as_view(), name='product_create'),
    path('products/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products_list'),
    path('products/<int:pk>/', adminapp.ProductsDetailView.as_view(), name='product_detail'),
    path('products/update/<int:pk>/', adminapp.ProductsUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductsDeleteView.as_view(), name='product_delete'),

    path('', adminapp.AdminHomeView.as_view(), name='admin_home'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superadmin/', include('adminapp.urls', namespace='superadmin')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('__debug__', include(debug_toolbar.urls)),
    path('', include('mainapp.urls')),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView,  DeleteView
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect


class AdminMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

    def get_test_func(self):
        return self.test_func

    def dispatch(self, request, *args, **kwargs):
        user_test_result = self.get_test_func()()
        if not user_test_result:
            return redirect('adminapp:forbidden')
        return super().dispatch(request, *args, **kwargs)


class ForbiddenView(TemplateView):
    template_name = 'adminapp/forbidden.html'


class AdminHomeView(LoginRequiredMixin, AdminMixin, TemplateView):
    template_name = 'adminapp/base.html'


# Users Views

class UsersListView(LoginRequiredMixin, AdminMixin, ListView):
    model = ShopUser
    context_object_name = 'users'
    template_name = 'adminapp/users/users_list.html'
    login_url = 'authapp:login'


class UsersDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = ShopUser
    context_object_name = 'user'
    template_name = 'adminapp/users/users_detail.html'
    login_url = 'authapp:login'


class UsersCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = ShopUser
    fields = '__all__'
    template_name = 'adminapp/users/users_create.html'
    login_url = 'authapp:login'


class UsersUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = ShopUser
    fields = '__all__'
    context_object_name = 'user'
    template_name = 'adminapp/users/users_edit.html'
    login_url = 'authapp:login'


class UsersDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = ShopUser
    context_object_name = 'user'
    template_name = 'adminapp/users/users_delete.html'
    success_url = reverse_lazy('superadmin:users_list')
    login_url = 'authapp:login'


# Categories Views

class CategoryListView(LoginRequiredMixin, AdminMixin, ListView):
    model = ProductCategory
    context_object_name = 'categories'
    template_name = 'adminapp/categories/category_list.html'
    login_url = 'authapp:login'


class CategoryDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = ProductCategory
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_detail.html'
    login_url = 'authapp:login'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        category_pk = self.kwargs.get('pk')
        context['products'] = Product.objects.filter(category=category_pk)
        return context


class CategoryCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = ProductCategory
    fields = '__all__'
    template_name = 'adminapp/categories/category_create.html'
    login_url = 'authapp:login'


class CategoryUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = ProductCategory
    fields = '__all__'
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_edit.html'
    login_url = 'authapp:login'


class CategoryDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = ProductCategory
    context_object_name = 'category'
    template_name = 'adminapp/categories/category_delete.html'
    success_url = reverse_lazy('superadmin:category_list')
    login_url = 'authapp:login'


# Products Views

class ProductsListView(LoginRequiredMixin, AdminMixin, ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'adminapp/products/products_list.html'
    login_url = 'authapp:login'


class ProductsDetailView(LoginRequiredMixin, AdminMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'adminapp/products/products_detail.html'
    login_url = 'authapp:login'


class ProductsCreateView(LoginRequiredMixin, AdminMixin, CreateView):
    model = Product
    fields = '__all__'
    template_name = 'adminapp/products/products_create.html'
    login_url = 'authapp:login'


class ProductsUpdateView(LoginRequiredMixin, AdminMixin, UpdateView):
    model = Product
    fields = '__all__'
    context_object_name = 'product'
    template_name = 'adminapp/products/products_edit.html'
    login_url = 'authapp:login'


class ProductsDeleteView(LoginRequiredMixin, AdminMixin, DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'adminapp/products/products_delete.html'
    login_url = 'authapp:login'

    def get_success_url(self):
        product = Product.objects.filter(id=self.kwargs['pk'])[0]
        category_pk = product.category.pk

        return reverse_lazy('superadmin:category_detail', kwargs={'pk': category_pk})

templates/adminapp/products/products_create.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Create Product
{% endblock title %}

{% block content %}
    <h1>New Product</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/adminapp/products/products_delete.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Delete {{ product.name }}
{% endblock title %}

{% block content %}
    <h1>Delete {{ product.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ product.name }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/adminapp/products/products_detail.html
{% extends 'adminapp/base.html' %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <div class="product-entry">
        <h2>{{ product.name }}</h2>
        <button>
            <a href={% url 'superadmin:product_update' product.pk %}>Edit</a>
        </button>
        <button>
            <a href={% url 'superadmin:product_delete' product.pk %}>Delete</a>
        </button>
        <br><br>
        <img src="/media/{{ product.full_image }}">
        <div class="product_description">
            <h3>Product Information:</h3>
            <ul class="product_info_list">
                <li><b>Name: </b>{{ product.name }}</li>
                <li><b>Category: </b>
                    <a href="{% url 'superadmin:category_detail' product.category.pk %}">
                        {{ product.category.name }}
                    </a>
                </li>
                <li><b>Price: </b>{{ product.price }} RUB</li>
                <li><b>Short Description: </b>{{ product.short_desc }}</li>
                <li><b>Full Description: </b>{{ product.full_desc }}</li>
                <li><b>Quantity: </b>{{ product.quantity }}</li>
            </ul>
        </div>
    <a href="{% url 'adminapp:category_detail' product.category.pk %}"
       class="btn btn-secondary btn-lg active btn-block"
       role="button" aria-pressed="true">Return
    </a>
    <br>
    </div>
{% endblock content %}

templates/adminapp/products/products_edit.html
{% extends 'adminapp/base.html' %}

{% block title %}
    Edit {{ product.name }}
{% endblock title %}

{% block content %}
    <h1>Edit {{ product.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/adminapp/products/products_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>